extends: jaid
# rules:
#   '@typescript-eslint/no-unsafe-assignment': 0
#   '@typescript-eslint/no-unsafe-member-access': 0
#   '@typescript-eslint/no-unsafe-return': 0
#   '@typescript-eslint/no-unsafe-argument': 0
