name: debug
on:
  workflow_call: {}
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: env
        shell: bash
        run: |
          keys=("${!env[@]}")
          sortedKeys=($(printf '%s\n' "${keys[@]}" | sort -u))
          for key in "${sortedKeys[@]}"; do
            printf '%s=%s\n' "$key" "${env[$key]}"
          done
