name: bump
on:
  workflow_call: {}
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: env
        shell: bash
        run: |
          keys=("${!env[@]}")
          sorted_keys=($(printf '%s\n' "${keys[@]}" | sort -u))
          for key in "${sorted_keys[@]}"; do
            printf '%s=%s\n' "$key" "${env[$key]}"
          done
