on:
  workflow_call:
    inputs:
      bases:
        description: List of base images, split by anything
        required: false
        type: string
      platform:
        description: List of platforms, split by anything
        required: false
        type: string
      additionEvals:
        description: List of additional values, javascript object code without outer braces
        required: false
        type: string
      flavorEval:
        description: JavaScript code to generate the flavor and id values
        required: false
        type: string
    outputs:
      output:
        description: The dynamically generated matrix in JSON
        value: ${{ jobs.job.outputs.output }}
      nativeArch:
        description: The dynamically generated matrix in JSON, filtered to only include native arch
        value: ${{ jobs.job.outputs.nativeArch }}
jobs:
  job:
    name: makeMatrix
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      output: ${{ steps.makeMatrix.outputs.value }}
      nativeArch: ${{ steps.makeMatrix.outputs.nativeArch }}
    steps:
      - name: setupNode
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest
      - name: checkout
        uses: actions/checkout@v3.5.2
      - name: installNodePackages
        id: installNodePackages
        uses: jaid/action-npm-install@main
      - id: makeMatrix
        name: makeMatrix
        run: node --import tsx .github/workflows/makeDockerTagMatrix-overlay/makeMatrix.ts
        env:
          inputs: ${{ toJSON(inputs) }}
          arch: ${{ runner.arch }}