name: pushDocker
on:
  workflow_call:
    inputs:
      arch:
        type: string
        required: false
        default: ''
        description: List of image archs to build, comma separated without spaces
      buildContext:
        type: string
        required: false
        default: src
      dockerHubUser:
        type: string
        required: false
        default: jaidchen
      dockerHubRegistry:
        type: string
        required: false
        default: docker.io
      githubRegistry:
        type: string
        required: false
        default: ghcr.io
      baseTags:
        type: string
        required: false
        default: |
          type=ref,event=branch
          type=schedule,pattern=nightly
          type=schedule,pattern={{date 'YYYYMMDD'}}
      shaTags:
        type: boolean
        required: false
        default: false
        description: If true, create a docker image tag named after the commit’s SHA hash (good for persistence and debugging, but will produce a lot of clutter)
      additionalTags:
        type: string
        required: false
        default: ''
      flavorLatest:
        type: string
        required: false
        default: auto
      flavorPrefix:
        type: string
        required: false
        default: ''
      flavorSuffix:
        type: string
        required: false
        default: ''
      # flavorPrefixLatest:
      #   type: string
      #   required: false
      #   default: auto
      # flavorSuffixLatest:
      #   type: string
      #   required: false
      #   default: auto
      buildArgs:
        type: string
        required: false
        default: ''
    secrets:
      dockerHubToken:
        required: false
        description: 'Create here with “Read, Write”: https://hub.docker.com/settings/security?generateToken=true'
    outputs:
      meta:
        value: ${{ jobs.job.outputs.meta }}
      digest:
        value: ${{ jobs.job.outputs.digest }}
      imageName:
        value: ${{ jobs.job.outputs.imageName }}
      imageSlug:
        value: ${{ jobs.job.outputs.imageSlug }}
jobs:
  job:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      meta: ${{ steps.dockerBuild.outputs.metadata }}
      digest: ${{ steps.dockerBuild.outputs.digest }}
      imageSlug: ${{ steps.dockerHubRef.outputs.ref }}
      imageName: ${{ steps.dockerHubRef.outputs.shortName }}
    steps:
      - name: dockerHubRef
        id: dockerHubRef
        shell: bash
        run: |
          repoName=${{ github.event.repository.name }}
          shortName=${repoName##docker-}
          printf 'ref=%s/%s\nshortName=%s' '${{ inputs.dockerHubUser }}' "$shortName" "$shortName" > $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up qemu
        uses: docker/setup-qemu-action@v2
      - name: Set up buildx
        uses: docker/setup-buildx-action@v2
      - name: getDockerHubTokenLength
        id: getDockerHubTokenLength
        shell: bash
        env:
          dockerHubToken: ${{ secrets.dockerHubToken }}
        run: |
          length=${#dockerHubToken}
          printf 'length=%s' "$length" > $GITHUB_OUTPUT
      - name: Login to ${{ inputs.dockerHubRegistry }}
        if: ${{ steps.getDockerHubTokenLength.outputs.length > 0 }}
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.dockerHubUser }}
          password: ${{ secrets.dockerHubToken }}
      - name: Login to ${{ inputs.githubRegistry }}
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.githubRegistry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: |
            ${{ inputs.githubRegistry }}/${{ github.repository }}
            ${{ steps.dockerHubRef.outputs.ref }}
          labels: |
            maintainer=${{ github.actor }}
            org.opencontainers.image.vendor=${{ github.actor }}
            org.opencontainers.image.title=${{ steps.dockerHubRef.outputs.shortName }}
          tags: |
            ${{ inputs.baseTags }}
            ${{ inputs.additionalTags }}
            ${{ fromJSON('["type=sha,format=long", ""]')[inputs.shaTags == true] }}
          # above hack from here: https://github.com/orgs/community/discussions/25725#discussioncomment-3248924
          flavor: |
            latest=${{ inputs.flavorLatest }}
            prefix=${{ inputs.flavorPrefix }}
            suffix=${{ inputs.flavorSuffix }}
          # prefixLatest=${{ inputs.flavorPrefixLatest }}
          # suffixLatest=${{ inputs.flavorSuffixLatest }}
      - name: getArch
        id: getArch
        shell: bash
        run: |
          if [[ -n $givenArch ]]; then
            arch=$givenArch
          elif [[ -f arch.lines ]]; then
            readarray -t archs < arch.lines
            function joinBy {
              local IFS="$1"; shift; echo "$*"
            }
            arch=$(joinBy , "${archs[@]}");
          else
           arch=linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
          fi
          printf 'arch=%s' "$arch" > $GITHUB_OUTPUT
        env:
          givenArch: ${{ inputs.arch }}
      - name: dockerBuild
        id: dockerBuild
        uses: docker/build-push-action@v4.0.0
        with:
          load: true
          context: ${{ inputs.buildContext }}
          platforms: ${{ steps.getArch.outputs.arch }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ${{ inputs.buildArgs }}
      - name: dockerPush
        id: dockerPush
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          context: ${{ inputs.buildContext }}
          platforms: ${{ steps.getArch.outputs.arch }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
